sdfsd

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,22 +15,21 @@ jobs:
       - browser-tools/install-browser-tools
       - node/install-packages
       - run:
-          command: npm run test
-      - store_test_results:
-          path: /tests_output
-     - run:
-          name: Check Test Result
-          command: |
-            if [ $? -eq 0 ]; then
-              echo "Tests passed, proceeding with code upload"
-            else
-              echo "Tests failed, code upload aborted"
-              circleci step halt
-            fi
-      - deploy:
           name: Upload to GitHub
-          command: |
-            # Add commands to push code to GitHub branch here
+          command: npm run test
+            if [ $? -eq 0 ]; then
+              # Tests passed, upload to GitHub
+              git config user.name "CircleCI"
+              git config user.email "<muhammad.muneeb@qenta.com>"
+              git add .
+              git commit -m "Passed tests [skip ci]"
+              git push origin HEAD:master
+            else
+              # Tests failed, exit with a non-zero code
+              exit 1
+            fi
+       - store_test_results:
+           path: /tests_output
 workflows:
   e2e-test:
     jobs:
